"""fresh_init

Revision ID: 64f291eb5aa5
Revises: 
Create Date: 2026-02-12 23:03:48.928158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f291eb5aa5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('integrity_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.String(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('metadata_log', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrity_violations_id'), 'integrity_violations', ['id'], unique=False)
    op.create_index(op.f('ix_integrity_violations_student_id'), 'integrity_violations', ['student_id'], unique=False)
    op.create_index(op.f('ix_integrity_violations_timestamp'), 'integrity_violations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_integrity_violations_violation_type'), 'integrity_violations', ['violation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrity_violations_violation_type'), table_name='integrity_violations')
    op.drop_index(op.f('ix_integrity_violations_timestamp'), table_name='integrity_violations')
    op.drop_index(op.f('ix_integrity_violations_student_id'), table_name='integrity_violations')
    op.drop_index(op.f('ix_integrity_violations_id'), table_name='integrity_violations')
    op.drop_table('integrity_violations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
