"""Add typing_baseline

Revision ID: 78961996a022
Revises: 64f291eb5aa5
Create Date: 2026-02-13 19:54:20.262965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78961996a022'
down_revision: Union[str, None] = '64f291eb5aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('typing_baseline', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'typing_baseline')
    # ### end Alembic commands ###
